version: '3.8'
services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    # image: laxmidhakal/python-app:${BUILD_NUMBER} # This is for Docker image
    ports:
      - "5000:5000"
